sync

diff --git a/arch/sparc64/conf/Makefile.sparc64 b/arch/sparc64/conf/Makefile.sparc64
--- a/arch/sparc64/conf/Makefile.sparc64
+++ b/arch/sparc64/conf/Makefile.sparc64
@@ -1,54 +1,137 @@
-# Makefile for OpenBSD
+# 	$NetBSD: Makefile.sparc64,v 1.67 2008/08/30 13:23:55 martin Exp $
 
+#=========================================================================
+#
+#			***** WARNING ******
+#
+# ANYONE WHO CHANGES THIS MAKEFILE AND DOES NOT TEST BOTH A 32-BIT
+# AND 64-BIT KERNEL WILL BE SHOT.
+#
+#=========================================================================
+
+
+# Makefile for NetBSD
+#
+# This makefile is constructed from a machine description:
+#	config machineid
+# Most changes should be made in the machine description
+#	/sys/arch/sparc64/conf/``machineid''
+# after which you should do
+#	config machineid
+# Machine generic makefile changes should be made in
+#	/sys/arch/sparc64/conf/Makefile.sparc64
+# after which config should be rerun for all machines of that type.
+#
+# To specify debugging, add the config line: makeoptions DEBUG="-g"
+# A better way is to specify -g only for a few files.
+#
+#	makeoptions DEBUGLIST="uvm* trap if_*"
+
+# Default to 32-bit.  Set the MACHINE_ARCH accordingly.
+#
+# You must also be using the correct toolchain or the kernel build
+# will fail.
+#
+LP64?=	no
+.if ${LP64} == "yes"
+MACHINE_ARCH=sparc64
+.else
+MACHINE_ARCH=sparc
+.endif
+
+USETOOLS?=	no
+NEED_OWN_INSTALL_TARGET?=no
 .include <bsd.own.mk>
 
-MKDEP?=	mkdep
-SIZE?=	size
-STRIP?=	strip
-
-# source tree is located via $S relative to the compilation directory
-.ifndef S
-S!=	cd ../../../..; pwd
-.endif
+##
+## (1) port identification
+##
 SPARC64=	$S/arch/sparc64
+GENASSYM_CONF=	${SPARC64}/sparc64/genassym.cf
 
-INCLUDES=	-nostdinc -I. -I$S -I$S/arch
-CPPFLAGS=	${INCLUDES} ${IDENT} -D_KERNEL
+##
+## (2) compile settings
+##
+CPPFLAGS+=	-Dsparc64 -D__sparc64__
+.if ${LP64} == "yes"
+# 64-bit kernels
+CPPFLAGS+=	-D_LP64 -Wa,-Av9a
+AFLAGS+=	-Wa,-Av9a
+CC_NOOPT=	${NORMAL_C}
+.if defined(PROF)
+# Profiling is only supported in the medium low memory model.
+CFLAGS+=	-mcmodel=medlow
+.else
+# Since the kernel resides in the lower 32 bits, use medium low for now anyway.
+CFLAGS+=	-mcmodel=medlow
+.endif
+.else
+# 32-bit kernels
+CPPFLAGS+=	-m32 -Wa,-Av8plusa -mcpu=ultrasparc
+AFLAGS+=	-Wa,-Av8plusa
+# XXX
+# The sparc gcc version 3.3.3 (NetBSD nb1 20040301) does not compile this
+# file properly with higher optimizations
+CC_NOOPT=	${NORMAL_C:C/-O./-O0/}
+.endif
+CFLAGS+=	-mno-fpu
+AFLAGS+=	-x assembler-with-cpp -traditional-cpp
 
-CDIAGFLAGS=	-Werror -Wall -Wstrict-prototypes -Wmissing-prototypes \
-		-Wno-uninitialized -Wno-format -Wno-main \
-		-Wstack-larger-than-2047 -Wvariable-decl
+##
+## (3) libkern and compat
+##
+# KERN_AS=	obj	# memcpy, memset, etc. are in locore.s
 
-CMACHFLAGS=	-Wa,-Av9a, -mno-fpu -fno-builtin-printf -fno-builtin-log
-.if ${IDENT:M-DNO_PROPOLICE}
-CMACHFLAGS+=	-fno-stack-protector
+##
+## (4) local objects, compile rules, and dependencies
+##
+MD_OBJS=	locore.o
+MD_CFILES=
+MD_SFILES=	${SPARC64}/sparc64/locore.s
+
+locore.o: ${SPARC64}/sparc64/locore.s assym.h
+	${NORMAL_S}
+
+##
+## (5) link settings
+##
+TEXTADDR?=	01000000
+LINKFORMAT=	-T ${SPARC64}/conf/${KERN_LDSCRIPT}
+.if ${LP64} == "yes"
+KERN_LDSCRIPT?= kern.ldscript
+.else
+KERN_LDSCRIPT?= kern32.ldscript
 .endif
 
-CFLAGS=		${DEBUG} -O2 ${CDIAGFLAGS} ${CMACHFLAGS} ${COPTS} ${PIPE}
-AFLAGS=		-x assembler-with-cpp -traditional-cpp -D_LOCORE -Wa,-Av9a
-LINKFLAGS=	-n -Ttext 01000000 -Tdata 01800000 -e start -N
-STRIPFLAGS=	-g -X -x
+##
+## (6) port specific target dependencies
+##
 
-HOSTCC=	${CC}
-HOSTED_CPPFLAGS=${CPPFLAGS:S/^-nostdinc$//}
-HOSTED_CFLAGS=	${CFLAGS}
+# depend on CPU configuration
+bwtwo.o cgsix.o cgthree.o cgtwo.o cons.o dma.o esp.o fb.o if_ie.o: Makefile
+ms.c obio.o zs.c autoconf.o clock.o cpu.o disksubr.o locore.o: Makefile
+machdep.o mem.o openprom.o pmap.o vm_machdep.o: Makefile
 
-# compile rules: rules are named ${TYPE}_${SUFFIX}${CONFIG_DEP}
-# where TYPE is NORMAL, DRIVER, or PROFILE}; SUFFIX is the file suffix,
-# capitalized (e.g. C for a .c file), and CONFIG_DEP is _C if the file
-# is marked as config-dependent.
+cpu_in_cksum.o lock_stubs.o: assym.h
 
-NORMAL_C_NOP=	${CC} ${CFLAGS} ${CPPFLAGS} -c $<
-NORMAL_C=	${CC} ${CFLAGS} ${CPPFLAGS} ${PROF} -c $<
-NORMAL_C_C=	${CC} ${CFLAGS} ${CPPFLAGS} ${PROF} ${PARAM} -c $<
+##
+## (7) misc settings
+##
 
-DRIVER_C=	${CC} ${CFLAGS} ${CPPFLAGS} ${PROF} -c $<
-DRIVER_C_C=	${CC} ${CFLAGS} ${CPPFLAGS} ${PROF} ${PARAM} -c $<
+# define .MAIN _before_ the make() check, so that implicit target
+# would be defined
+.MAIN: all
 
-NORMAL_S=	${CC} ${AFLAGS} ${CPPFLAGS} -c $<
-NORMAL_S_C=	${CC} ${AFLAGS} ${CPPFLAGS} ${PARAM} -c $<
+.if make(depend) || make(all) || make(dependall)
+.BEGIN:
+	@rm -f sparc && \
+		ln -s $S/arch/sparc/include sparc
+.endif
 
-HOSTED_C=	${HOSTCC} ${HOSTED_CFLAGS} ${HOSTED_CPPFLAGS} -c $<
+##
+## (8) config(8) generated machinery
+##
+%INCLUDES
 
 %OBJS
 
@@ -56,101 +139,19 @@ HOSTED_C=	${HOSTCC} ${HOSTED_CFLAGS} ${HOSTED_CPPFLAGS} -c $<
 
 %SFILES
 
-# load lines for config "xxx" will be emitted as:
-# xxx: ${SYSTEM_DEP} swapxxx.o
-#	${SYSTEM_LD_HEAD}
-#	${SYSTEM_LD} swapxxx.o
-#	${SYSTEM_LD_TAIL}
-SYSTEM_OBJ=	locore.o param.o ioconf.o ${OBJS}
-SYSTEM_DEP=	Makefile ${SYSTEM_OBJ}
-SYSTEM_LD_HEAD=	@rm -f $@
-SYSTEM_LD=	@echo ${LD} ${LINKFLAGS} -o $@ '$${SYSTEM_OBJ}' vers.o; \
-		${LD} ${LINKFLAGS} -o $@ ${SYSTEM_OBJ} vers.o
-SYSTEM_LD_TAIL=	@${SIZE} $@; chmod 755 $@
-
-DEBUG?=
-.if ${DEBUG} == "-g"
-LINKFLAGS+=	-X
-SYSTEM_LD_TAIL+=; \
-		echo mv $@ $@.gdb; rm -f $@.gdb; mv $@ $@.gdb; \
-		echo ${STRIP} ${STRIPFLAGS} -o $@ $@.gdb; \
-		${STRIP} ${STRIPFLAGS} -o $@ $@.gdb
-.else
-LINKFLAGS+=	-S -x
-.endif
-
 %LOAD
 
-assym.h: $S/kern/genassym.sh ${SPARC64}/sparc64/genassym.cf Makefile
-	sh $S/kern/genassym.sh ${CC} ${CFLAGS} ${CPPFLAGS} \
-	    ${PARAM} < ${SPARC64}/sparc64/genassym.cf > assym.h.tmp && \
-	    mv -f assym.h.tmp assym.h
-
-param.c: $S/conf/param.c
-	rm -f param.c
-	cp $S/conf/param.c .
-
-param.o: param.c Makefile
-	${NORMAL_C_C}
-
-mcount.o: $S/lib/libkern/mcount.c Makefile
-	${NORMAL_C_NOP}
-
-ioconf.o: ioconf.c
-	${NORMAL_C}
-
-newvers: ${SYSTEM_DEP} ${SYSTEM_SWAP_DEP}
-	sh $S/conf/newvers.sh
-	${CC} ${CFLAGS} ${CPPFLAGS} ${PROF} -c vers.c
-
-
-clean::
-	rm -f eddep *bsd *bsd.gdb tags *.[io] [a-z]*.s \
-	    [Ee]rrs linterrs makelinks genassym genassym.o assym.h
-
-lint:
-	@lint -hbxncez -DGENERIC -Dvolatile= ${CPPFLAGS} ${PARAM} -UKGDB \
-	    ${CFILES} ioconf.c param.c | \
-	    grep -v 'static function .* unused'
-
-tags:
-	@echo "see $S/kern/Makefile for tags"
-
-links:
-	egrep '#if' ${CFILES} | sed -f $S/conf/defines | \
-	  sed -e 's/:.*//' -e 's/\.c/.o/' | sort -u > dontlink
-	echo ${CFILES} | tr -s ' ' '\12' | sed 's/\.c/.o/' | \
-	  sort -u | comm -23 - dontlink | \
-	  sed 's,../.*/\(.*.o\),rm -f \1; ln -s ../GENERIC/\1 \1,' > makelinks
-	sh makelinks && rm -f dontlink
-
-SRCS=	${SPARC64}/sparc64/locore.s \
-	param.c ioconf.c ${CFILES} ${SFILES}
-depend:: .depend
-.depend: ${SRCS} assym.h param.c
-	${MKDEP} ${AFLAGS} ${CPPFLAGS} ${SPARC64}/sparc64/locore.s
-	${MKDEP} -a ${CFLAGS} ${CPPFLAGS} param.c ioconf.c ${CFILES}
-.if !empty(SFILES)
-	${MKDEP} -a ${AFLAGS} ${CPPFLAGS} ${SFILES}
-.endif
-	sh $S/kern/genassym.sh ${MKDEP} -f assym.dep ${CFLAGS} \
-	    ${CPPFLAGS} < ${SPARC64}/sparc64/genassym.cf
-	@sed -e 's/.*\.o:.* /assym.h: /' < assym.dep >> .depend
-	@rm -f assym.dep
-
-locore.o: ${SPARC64}/sparc64/locore.s assym.h
-	${NORMAL_S}
-
-# The install target can be redefined by putting a
-# install-kernel-${MACHINE_NAME} target into /etc/mk.conf
-MACHINE_NAME!=  uname -n
-install: install-kernel-${MACHINE_NAME}
-.if !target(install-kernel-${MACHINE_NAME}})
-install-kernel-${MACHINE_NAME}:
-	rm -f /obsd
-	ln /bsd /obsd
-	cp bsd /nbsd
-	mv /nbsd /bsd
-.endif
-
 %RULES
+
+## Include rules for Atheros WLAN
+.include "$S/contrib/dev/ath/netbsd/Makefile.ath.inc"
+
+##
+## (9) port independent kernel machinery
+##
+.include "$S/conf/Makefile.kern.inc"
+
+##
+## (10) Appending make options.
+##
+%MAKEOPTIONSAPPEND
